name: Florian Hartmann
favicon: null
layout_spectrum: 0.2638298
typography_spectrum: 0.2106383
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#25272A'
    - '#A5A7AA'
    - '#FF3B30'
  brandStrength: 0.8125
  lightness: 0.6787234
  saturation: 0.6875
  rhythmicContrast: 0.5978723
purpose: []
